
# Dictionaries
# A dictionary is a collection which is unordered, changeable and indexed. 
# A dictionary consists of a collection of key-value pairs. 
# Each key-value pair maps the key to its associated value.
#  A dictionary is written in braces. Each key is separated from its value by a colon (:), 
#  and the items are separated by commas.

my_dict = {"name":"Max", "age":28, "city":"New York"}