#LISTS
# Unlike Sets, Lists allow duplicate elements. 
 #They are useful for preserving a sequence of data and further iterating over it. 
 #Lists are created with square brackets.

my_list = ["banana", "cherry", "apple"]

# Comparison of basic built-in collection data types in Python:
# List is a collection which is ordered and mutable. Allows duplicate members.
# Tuple is a collection which is ordered and immutable. Allows duplicate members.
# Set is a collection which is unordered and unindexed. No duplicate members.
# Dictionary is a collection which is unordered, mutable and indexed. No duplicate members.
# Strings are immutable sequences of Unicode code points.