
# Tuple
# A tuple is a collection of objects which is ordered and immutable.
#  Tuples are similar to lists, the main difference ist the immutability.
#   In Python tuples are written with round brackets and comma separated values.

my_tuple = ("Max", 28, "New York")

# Reasons to use a tuple over a list
# Generally used for objects that belong together.
# Use tuple for heterogeneous (different) datatypes and list for homogeneous (similar) datatypes.
# Since tuple are immutable, iterating through tuple is slightly faster than with list.
# Tuples with their immutable elements can be used as key for a dictionary. This is not possible with lists.
# If you have data that doesn't change, implementing it as tuple will guarantee that it remains write-protected.